os:
  - linux

dist: xenial

language: python
addons:
  sonarcloud:
    organization: "santhosh1234"
    token:
      secure: "w6VOyBmnNoneBf4o4gbsJscQj0BwCXeI171vAdPwSSRIK9qc2cK3nQJjaXkWWknDKBniqFRYbWQFgrUK6Ibu+VHy6MEsM4Qu9HD01I2RyyWct7kS78Yruypkdfqyf8ohOmQlzuInGT3OQur59UC72cQ/OdHHORE10ZHf00W6/Uw44DW8/JSSa6FS6YSOmX6Nnxm6JQtEMKUz1WWIyrqTSwosE8koHb4R2QJiKDAm9aCc6mgAA1Ibo/RV5zXAah+qf44wrS9OVmDZrcbpsCwRA6biplj/3mBxc0KLn9liU+Zoh8NhGKrll6HGleeI3qGx/nvs4N6/TFhc8vwJ7++k4aW9USRE2rTz1xNiD9NgyBgiAmIvmZQLn6G06kBd9HkuOZcWgAa/gmZ4OdOD5Qsl57TWEFLSuzTSefqc6Qu6Lgo3mQUt3hb1Vf2mPFmpPNQgQGWw7GzGsCqEq2x7WncatFK/qO7+JPHYreB7PDsCExMKp73oyCDmnF4ZobK3m6uKN1cjMjFIqfeWuGZdYahvfogyXOUdP5Dhl7O2KT+XSBOCaG9iM4igxZxwLq8AGWW93RB50lHebWioH6z9Rye/sqfAoNZJtq/6I+XEY20t4HHua60uljszImx0lXJrnAbSKrH3kZ/HoWiL8J/04qkn2Ki1j21RB9ttar6rULaJakk=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
script:
  - python -m pytest -v
  - sonar-scanner
